Repository jenkins-x/jenkins-x-boot-config, pull requests merged in 2019-10, with the labels that each got.

#68 WIP: script which upserts domains for testing
  bdd/upsert_bdd_domains.sh
Labels: approved, do-not-merge/work-in-progress, size/M

#75 fix: enable injection of the docker registry from requirements
  bdd/boot-vault/jx-requirements.yml
  env/jenkins-x-platform/values.tmpl.yaml
  env/jxboot-resources/values.tmpl.yaml
  env/lighthouse/values.tmpl.yaml
  jenkins-x-bdd-local.yml
  jenkins-x-bdd-vault.yml
  kubeProviders/gke/values.tmpl.yaml
Labels: approved, lgtm, size/M

#76 fix: Turn on metapipeline by default
  env/prow/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#74 feat: add IRSA templates to enable fine-grained permissions
  kubeProviders/eks/templates/irsa.tmpl.yaml
  kubeProviders/eks/templates/jenkinsx-policies.yml
Labels: approved, lgtm, size/M

#78 fix: disable populating the docker cfg secret by default for IKS + PKS
  kubeProviders/iks/values.tmpl.yaml
  kubeProviders/pks/values.tmpl.yaml
Labels: approved, lgtm, size/S

#79 feat: add step to verify the parameters on pull request pipeline
  jenkins-x.yml
Labels: approved, lgtm, size/L

#82 fix: use the proper name for schema file when validating the paramters
  jenkins-x.yml
Labels: size/XS

#83 chore: remove the parameters schema since is generated from the template
  .gitignore
  env/.gitignore
  env/parameters.schema.json
Labels: size/L

#72 add option to set google project
  systems/external-dns/values.tmpl.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#80 fix: Add support for GitPublic field in requirements
  env/jxboot-resources/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#84 chore: disable vault URL discovery in the pipeline file
  jenkins-x-bdd-vault.yml
Labels: size/XS

#81 fix: verify-preinstall
  jenkins-x.yml
Labels: approved, lgtm, ok-to-test, size/XS

#88 fix: remove the bdd test for boot vault with TLS
  bdd/boot-vault/README.md
  bdd/boot-vault/cluster.yaml
  bdd/boot-vault/jx-requirements.yml
  bdd/boot-vault/parameters.yaml
  bdd/upsert_bdd_domains.sh
  jenkins-x-bdd-vault.yml
Labels: size/L

#87 fix: adding missing apiVersion to Helm Charts
  env/Chart.yaml
  repositories/Chart.yaml
  systems/vault/Chart.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#89 fix: external-dns values for provider EKS
  systems/external-dns/values.tmpl.yaml
Labels: approved, lgtm, ok-to-test, size/XS
