Repository jenkins-x/jenkins-x-boot-config, pull requests merged in 2019-11, with the labels that each got.

#85 feat: add ability to configure exposer
  env/jxboot-resources/values.tmpl.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#94 fix: allow bucketrepo to be used as a repository
  env/bucketrepo/values.tmpl.yaml
  env/jenkins-x-platform/values.tmpl.yaml
  env/nexus/values.tmpl.yaml
  env/nexus/values.yaml
  env/requirements.yaml
Labels: approved, lgtm, size/M

#95 fix: disable chart museum
  env/chartmusem/values.tmpl.yaml
  env/jenkins-x-platform/values.tmpl.yaml
Labels: approved, lgtm, size/S

#97 fix: use of Requirements.repository
  env/bucketrepo/values.tmpl.yaml
  env/chartmusem/values.tmpl.yaml
  env/jenkins-x-platform/values.tmpl.yaml
Labels: approved, lgtm, size/M

#100 fix: use correct folder name for chartmuseum
  env/chartmuseum/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#99 fix: Add verify-fmt and fmt, fail PR if not formatted
  Makefile
  jenkins-x-bdd-local.yml
  jenkins-x.yml
Labels: approved, lgtm, size/L

#90 fix: added velero configuration for iks
  systems/velero/values.tmpl.yaml
Labels: approved, lgtm, ok-to-test, size/S

#101 feat: add eks vault configuration
  jenkins-x.yml
  kubeProviders/eks/templates/jenkinsx-policies.yml
  kubeProviders/eks/templates/vault_cf_tmpl.yml
Labels: approved, lgtm, size/L

#102 fix: lets default PKS to use the internal docker registry OOTB
  kubeProviders/pks/values.tmpl.yaml
Labels: approved, size/S

#91 fix: Indent docker credential
  env/tekton/values.tmpl.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#103 feat: pks configuration to use dockerhub as default provider and mount local secrets as a volume
  env/parameters.tmpl.schema.json
  jenkins-x.yml
  kubeProviders/pks/values.tmpl.yaml
Labels: approved, lgtm, size/M

#106 feat: configuration for cert-manager in EKS and new APIs for the new versions
  jenkins-x.yml
  kubeProviders/eks/templates/irsa.tmpl.yaml
  kubeProviders/eks/templates/jenkinsx-policies.yml
  systems/acme/templates/cert-manager-prod-certificate.yaml
  systems/acme/templates/cert-manager-prod-issuer.yaml
  systems/acme/templates/cert-manager-staging-certificate.yaml
  systems/acme/templates/cert-manager-staging-issuer.yaml
  systems/acme/values.tmpl.yaml
  systems/cm/values.tmpl.yaml
  systems/external-dns/values.tmpl.yaml
Labels: approved, lgtm, size/L

#108 chore: lets label the certmanager certificate resources so it is easy …
  systems/acme/templates/cert-manager-prod-certificate.yaml
  systems/acme/templates/cert-manager-staging-certificate.yaml
Labels: approved, lgtm, size/XS

#107 fix: Revert "feat: configuration for cert-manager in EKS and new APIs for the new versions"
  OWNERS
  jenkins-x.yml
  kubeProviders/eks/templates/irsa.tmpl.yaml
  kubeProviders/eks/templates/jenkinsx-policies.yml
  systems/acme/templates/cert-manager-prod-certificate.yaml
  systems/acme/templates/cert-manager-prod-issuer.yaml
  systems/acme/templates/cert-manager-staging-certificate.yaml
  systems/acme/templates/cert-manager-staging-issuer.yaml
  systems/acme/values.tmpl.yaml
  systems/cm/values.tmpl.yaml
  systems/external-dns/values.tmpl.yaml
Labels: approved, lgtm, size/L

#111 chore: Update ci.sh for import/qs with local creds
  bdd/bdd.sh
Labels: approved, lgtm, size/XS

#104 docs: fix link in README.md
  README.md
Labels: approved, lgtm, size/XS
