Repository jenkins-x/jenkins-x-boot-config, pull requests merged in 2019-09, with the labels that each got.

#52 fix: revert files removed
  systems/acme/templates/cert-manager-prod-certificate.yaml
  systems/acme/templates/cert-manager-prod-issuer.yaml
  systems/acme/templates/cert-manager-staging-certificate.yaml
  systems/acme/templates/cert-manager-staging-issuer.yaml
Labels: approved, lgtm, size/M

#54 fix: use namespace from jx-requirements
  jenkins-x-bdd-local.yml
  jenkins-x-bdd-vault.yml
  jenkins-x.yml
Labels: approved, lgtm, size/S

#56 fix: Revert "fix: use namespace from jx-requirements"
  jenkins-x-bdd-local.yml
  jenkins-x-bdd-vault.yml
  jenkins-x.yml
Labels: approved, lgtm, size/S

#55 feat: add a release pipeline which generates the chanelog
  jenkins-x-release.yml
Labels: size/S

#57 fix: enable ingress based on webhook configuration
  env/jxboot-resources/values.tmpl.yaml
Labels: approved, lgtm, size/S

#53 feat: update the vault bdd requirements to use external-dns and TLS
  bdd/bdd.sh
  bdd/boot-vault/jx-requirements.yml
  env/jenkins/values.tmpl.yaml
  env/jxboot-resources/README.MD
  env/parameters.schema.json
  jenkins-x-bdd-local.yml
  jenkins-x-bdd-vault.yml
  jenkins-x-release.yml
  jenkins-x.yml
Labels: approved, lgtm, size/M

#58 chore: use for vault BDD the builder images version from version stream
  jenkins-x-bdd-vault.yml
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#62 fix: mount secrets into a non workspace dir to avoid checking out cod…
  .pre-commit-config.yaml
  .secrets.baseline
  bdd/bdd.sh
  jenkins-x-bdd-local.yml
  jenkins-x-bdd-vault.yml
Labels: size/L

#63 Improve bash options
  bdd/bdd.sh
Labels: approved, size/XS

#64 fix: BDD tests, use the new BD test GCP project
  bdd/bdd.sh
  bdd/boot-local/cluster.yaml
  bdd/boot-local/jx-requirements.yml
  bdd/boot-vault/cluster.yaml
  bdd/boot-vault/jx-requirements.yml
  jenkins-x-bdd-local.yml
Labels: approved, lgtm, size/S

#60 chore: store pipelineuser email
  env/jxboot-resources/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#67 fix: set the environment variables directly from secrets instead of using step credential command
  bdd/bdd.sh
  jenkins-x-bdd-local.yml
  jenkins-x-bdd-vault.yml
Labels: approved, lgtm, size/M

#65 Fix: new vault name location
  bdd/bdd.sh
  bdd/boot-local/jx-requirements.yml
  bdd/boot-vault/jx-requirements.yml
  jenkins-x-bdd-local.yml
  jenkins-x-bdd-vault.yml
  systems/vault/vault-ing.tmpl.yaml
Labels: approved, lgtm, size/S
