Repository jenkins-x/jenkins-x-boot-config, pull requests merged in 2020-05, with the labels that each got.

#153 fix: use the correct kaniko credsStore
  kubeProviders/aks/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#156 fix: making sure that custom, non default Docker registry can be used…
  kubeProviders/eks/values.tmpl.yaml
  kubeProviders/gke/values.tmpl.yaml
Labels: approved, lgtm, size/M

#154 feat: configure boot for Openshift with restricted permissions
  env/jenkins-x-platform/values.tmpl.yaml
  env/jxboot-resources/values.tmpl.yaml
  env/lighthouse/values.tmpl.yaml
  env/tekton/values.tmpl.yaml
  env/values.tmpl.yaml
Labels: approved, lgtm, size/L

#157 fix: Copy jx dependencies into temp JX_HOME
  bdd/bdd.sh
Labels: approved, lgtm, size/XS

#155 fix: Less confusing wording for Docker Registry configuration
  env/parameters.tmpl.schema.json
Labels: approved, lgtm, size/XS

#160 fix: Ensure we pass a string to the default admin password hashing
  env/jenkins-x-platform/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#161 fix: use correct value as cluster.provider for Azure ("aks")
  systems/velero/values.tmpl.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#162 fix: Use gcr.io/jenkinsxio for nginx-ingress-controller image
  systems/jxing/values.tmpl.yaml
Labels: approved, lgtm, size/XS
