Repository jenkins-x/jenkins-x-boot-config, pull requests merged in 2020-01, with the labels that each got.

#110 fix: use NLB for jxing in AWS
  systems/jxing/values.tmpl.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#105 fix: make it easier for users to edit environmentGitPublic
  jx-requirements.yml
Labels: approved, lgtm, size/XS

#109 fix: Fill mandatory tls field for jxboot chart
  env/jxboot-resources/values.tmpl.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#122 fix: generate the jx auth config in a configmap
  env/jxboot-resources/values.tmpl.yaml
  jenkins-x.yml
  systems/jx-auth/Chart.yaml
  systems/jx-auth/jx-auth-configmap.tmpl.yaml
  systems/jx-auth/templates/jx-auth-configmap.yaml
Labels: approved, lgtm, size/M

#123 fix: Revert "fix: generate the jx auth config in a configmap"
  env/jxboot-resources/values.tmpl.yaml
  jenkins-x.yml
  systems/jx-auth/Chart.yaml
  systems/jx-auth/jx-auth-configmap.tmpl.yaml
  systems/jx-auth/templates/jx-auth-configmap.yaml
Labels: approved, lgtm, size/M

#118 feat: Make remote and namespace configurable for staging and production
  env/jxboot-resources/values.tmpl.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#115 fix: Only use docker-credential-ecr-login for ecr
  kubeProviders/eks/values.tmpl.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#124 fix: generate the jx auth config in a configmap
  env/jxboot-resources/values.tmpl.yaml
  jenkins-x.yml
  systems/jx-auth/Chart.yaml
  systems/jx-auth/jx-auth-configmap.tmpl.yaml
  systems/jx-auth/templates/jx-auth-configmap.yaml
Labels: approved, lgtm, size/M

#126 fix: generate the jx auth config in a configmap
  env/jxboot-resources/values.tmpl.yaml
  jenkins-x.yml
  systems/jx-auth/Chart.yaml
  systems/jx-auth/jx-auth-configmap.tmpl.yaml
  systems/jx-auth/templates/jx-auth-configmap.yaml
Labels: approved, lgtm, size/M

#128 fix: Use cert manager 0.11 crds with dex
  env/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#130 feat: fix vault DynamoDB permissions
  kubeProviders/eks/templates/vault_cf_tmpl.yml
Labels: approved, lgtm, size/XS

#131 feat: add jxui's Service Account to IRSA under S3 Full Access to be able to download logs
  kubeProviders/eks/templates/irsa.tmpl.yaml
Labels: approved, lgtm, size/XS

#129 fix: define the domains of all environments in the external-dns domain filters
  systems/external-dns/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#132 chore: add autoupdate boot template values
  env/jxboot-resources/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#133 chore: Pass whether vault is enabled and clusterName to LH and Prow charts
  env/lighthouse/values.tmpl.yaml
  env/prow/values.tmpl.yaml
Labels: approved, lgtm, size/S

#134 chore: Pass pipelineUser as user to Lighthouse chart
  env/lighthouse/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#136 chore: configure velero plugins
  systems/velero/values.tmpl.yaml
Labels: approved, lgtm, size/S

#137 chore: disable volume snapshot backups
  systems/velero/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#135 chore: Pass the pipelineUser token to the Lighthouse chart
  env/lighthouse/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#138 fix: typo in initContainers word
  systems/velero/values.tmpl.yaml
Labels: approved, lgtm, ok-to-test, size/XS
